In [ ]:
#Experiment 11: Create Data Set and Load Data Set In Pandas Library
#Name:Shravya Srivastava
#PRN:25070123106

In [ ]:
#dataset creation
import pandas as pd
data={
    "rollno":[101,102,103,104,105],
    "gender":["female","male","female","male","female"],
    "department":["computer","it","entc","aiml","mechanical"],
    "cgpa":[8.1,6.4,9.2,9.0,6.7]
}
df=pd.DataFrame(data)
print(df)#creates table with 4 columns dictionary is converted to tabular form
#df to csv (excel format)

   rollno  gender  department  cgpa
0     101  female    computer   8.1
1     102    male          it   6.4
2     103  female        entc   9.2
3     104    male        aiml   9.0
4     105  female  mechanical   6.7

In [ ]:
df.to_csv("data.csv",index=False)
print(df)
#can be acssessed in the file and when downlaoded it ca be opened in excel sheet

   rollno  gender  department  cgpa
0     101  female    computer   8.1
1     102    male          it   6.4
2     103  female        entc   9.2
3     104    male        aiml   9.0
4     105  female  mechanical   6.7

In [ ]:
df.shape

(5, 4)

In [ ]:
df.size

20

In [ ]:
df.info ()# info abt data types with storage used and names of coloumns
#memory type
#data type
#non null no missing element
#pandas lib mein str is not defined hence under object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rollno      5 non-null      int64
 1   gender      5 non-null      object
 2   department  5 non-null      object
 3   cgpa        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe()
#statistical analysis: mean std min percentage only on numerical vale
#shouldnt be on rolll number only on marks/cg
#count tells non null values
#25%,50%and 70% are quartile :no meaning. here, helps find outliers:divides the data in 4 parts

           rollno      cgpa
count    5.000000  5.000000
mean   103.000000  7.880000
std      1.581139  1.287245
min    101.000000  6.400000
25%    102.000000  6.700000
50%    103.000000  8.100000
75%    104.000000  9.000000
max    105.000000  9.200000

In [ ]:
#uploading the dataset
import pandas as pd #always write this
import numpy as np
df=pd.read_csv('/content/Cars93.csv')#uplaod file copy path from here
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.size

930

In [ ]:
df.shape

(93, 10)

In [ ]:
df.info() #93 non null values so no null value in manufactures

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:


df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [ ]:
df.head()#displays first 5 rows

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.tail()#last 5 rows

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.sample(5)#any 5 random rows

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
72,Pontiac,LeMans,Small,9.0,31,NaN,74,4,25.5,17.0
53,Mazda,Protege,Small,11.6,28,NaN,103,5,26.5,13.0
81,Subaru,Legacy,Compact,19.5,23,Driver only,130,5,27.0,14.0
87,Volkswagen,Fox,Small,9.1,25,NaN,81,4,26.0,10.0
13,Chevrolet,Camaro,Sporty,15.1,19,Driver & Passenger,160,4,25.0,13.0

In [ ]:
df.isnull().sum() #adds all the null values only

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
df.duplicated().sum()#tells duplicsted value nonw

np.int64(0)

In [ ]:
df.nunique() #tells unique values

Manufacturer      32
Model             93
Type               6
Price             81
MPG.city          21
AirBags            2
Horsepower        57
Passengers         6
Rear.seat.room    24
Luggage.room      16
dtype: int64